copy_products/activities/urls.py
from django.urls import path

from . import views

app_name = 'activities'

urlpatterns = [
    path('install/', views.install, name='install'),
    path('uninstall/', views.uninstall, name='uninstall'),
    path('copy-products/', views.copy_products, name='copy-products'),
]

copy_products/copy_products/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('settings.urls', namespace='settings')),
    path('install/', include('core.urls', namespace='core')),
    path('activities/', include('activities.urls', namespace='activities')),
    path('admin/', admin.site.urls),
]

copy_products/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.install, name='install'),
]

copy_products/settings/urls.py
from django.urls import path
from settings import views

app_name = 'settings'

urlpatterns = [
    path('', views.index, name='index')
]

copy_products/settings/models.py
from core.models import Portals
from django.db import models


class SettingsPortal(models.Model):
    """Model for settings portal."""
    portal = models.OneToOneField(
        Portals,
        verbose_name='Портал',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'Настройка портала'
        verbose_name_plural = 'Настройки портала'

        ordering = ['portal', 'pk']

    def __str__(self):
        return 'Настройки для портала {}'.format(self.portal.name)

copy_products/settings/views.py
from activities.models import Activity
from core.bitrix24.bitrix24 import ActivityB24
from core.models import Portals
from django.conf import settings
from django.shortcuts import get_object_or_404, render
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt


@xframe_options_exempt
@csrf_exempt
def index(request):
    """View index page settings."""
    if request.method == 'POST':
        member_id: str = request.POST['member_id']
    elif request.method == 'GET':
        member_id: str = request.GET.get('member_id')
    else:
        return render(request, 'error.html', {
            'error_name': 'QueryError',
            'error_description': 'Неизвестный тип запроса'
        })

    portal: Portals = get_object_or_404(Portals, member_id=member_id)
    portal.check_auth()

    activities: Activity = Activity.objects.all()

    try:
        activities_installed = ActivityB24(portal,
                                           obj_id=None).get_all_installed()
    except RuntimeError as ex:
        return render(request, 'error.html', {
            'error_name': ex.args[0],
            'error_description': ex.args[1]
        })

    context = {
        'activities': activities,
        'activities_installed': activities_installed,
        'member_id': member_id,
        'app_name': settings.APP_NAME,
    }
    return render(request, 'settings/index.html', context)

copy_products/templates/settings/index.html
{% extends 'base.html' %}

{% block title %}Настройки {{ app_name }}{% endblock %}
{% block content %}
  <div class="container mt-5">
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
      {% for activity in activities %}
        <div class="col mb-2 d-flex align-items-stretch">
          <div class="card p-2">
            <div class="card-header fw-bold">
              {{ activity.name }}
            </div>
            <div class="card-body">
              <p>{{ activity.description }}</p>
              {% if activity.code in activities_installed %}
                <div class="alert alert-success" id="div-install-{{ activity.code }}">Установлено</div>
                <div class="alert alert-danger" id="div-uninstall-{{ activity.code }}" hidden>Не установлено</div>
              {% else %}
                <div class="alert alert-success" id="div-install-{{ activity.code }}" hidden>Установлено</div>
                <div class="alert alert-danger" id="div-uninstall-{{ activity.code }}">Не установлено</div>
              {% endif %}
            </div>
            <div class="card-footer">
              <button class="btn btn-success" onclick="installActivity('{{ activity.code }}')">Установить</button>
              <button class="btn btn-danger" onclick="uninstallActivity('{{ activity.code }}')">Удалить</button>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}
{% block user_scripts %}
  <script>
    function installActivity(code) {
        let div_install = document.getElementById('div-install-' + code);
        let div_uninstall = document.getElementById('div-uninstall-' + code);
        $.ajax({
            url: "{% url 'activities:install' %}",
            type: "POST",
            data: {code: code, member_id: "{{ member_id }}"},
        })
            .done(function (response) {
                if (response.result === true) {
                    alert('Активити успешно установлено на портал');
                    div_uninstall.hidden = true;
                    div_install.hidden = false;
                }
                else {
                    alert('Установка активити завершилась неудачно. Ошибка: ' + response.error_name + ' Описание ошибки: ' + response.error_description);
                }
            })
            .fail(function () {
                alert('Установка активити завершилось неудачно. Неизвестный тип ошибки');
            });
    }
    function uninstallActivity(code) {
        let div_install = document.getElementById('div-install-' + code);
        let div_uninstall = document.getElementById('div-uninstall-' + code);
        $.ajax({
            url: "{% url 'activities:uninstall' %}",
            type: "POST",
            data: {code: code, member_id: "{{ member_id }}"},
        })
            .done(function (response) {
                if (response.result === true) {
                    alert('Активити успешно удалено с портала');
                    div_uninstall.hidden = false;
                    div_install.hidden = true;
                }
                else {
                    alert('Удаление активити завершилось неудачно. Ошибка: ' + response.error_name + ' Описание ошибки: ' + response.error_description);
                }
            })
            .fail(function () {
                alert('Удаление активити завершилось неудачно. Неизвестный тип ошибки');
            });
    }
  </script>
{% endblock %}